server:
  port: 9101

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  mail:
    host: smtp.mailplug.co.kr
    port: 465
    protocol: smtp
    username: starruckus_blue@emotiv.kr
    password: email123!
    properties:
      debug: true
      smtp.ssl.enable: true
      mail.smtp.auth: false
      mail.smtp.starttls.enable: true

## swagger
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter : alpha
    doc-expansion : none
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json